### ISSUE TITLE
[BUG] Installation problem on Mac Os Big Sur

### ISSUE THREAD

**Issue by gerardjk** [terra-money/classic-core#556]
When following the installation instructions on MacOs Big Sur I am encountering the following error from `make install` which is preventing successful installation

go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.2-2-gf41a7de -X github.com/cosmos/cosmos-sdk/version.Commit=f41a7de7e1c06ab836d50381c6fe918b64a73483 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath ./cmd/terrad
\# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here

**Is anyone able to give advice on overcoming this problem?**

**Comment by YunSuk-Yeo** [comment]
@gerardjk that seems successful message. any problem after installation?

**Comment by cryptoboole** [comment]
Yes I am getting the same thing, guessing this has to do with M1 architecture. This is what happens when trying to run the binary too

```bash
dyld: Library not loaded: @rpath/libwasmvm.dylib
  Referenced from: /usr/local/bin/terrad
  Reason: image not found
[1]    62009 abort      terrad --help
```

**Comment by cryptoboole** [comment]
It seems this is still in effect https://github.com/terra-money/core/issues/548#issuecomment-910185567

**Comment by ZakAyesh** [comment]
I am also encountering this same message, but have an intel chip installed. 
System Details:
macOS Big Sur Version 11.6
Processor: Intel Core i7
GoLang: v1.16.8

**Comment by harryscholes** [comment]
@cryptoboole what commit are you doing this on? It works for me on v0.5.6

**Comment by harryscholes** [comment]
11.4

**Comment by harryscholes** [comment]
Related Cosmos SDK issues:
https://github.com/cosmos/cosmos-sdk/issues/10267
https://github.com/cosmos/cosmos-sdk/issues/5759

**Comment by Halimao** [comment]
hi guys, any new progress? I am encountering the same issue on mac air too
`terrad --help
dyld: Library not loaded: @rpath/libwasmvm.dylib
  Referenced from: /Users/xxx/Desktop/terra/./terrad
  Reason: image not found`

**Comment by ElasticBottle** [comment]
having the same issue with mac `12.1` @cryptoboole @harryscholes were you guys able to get up and running? Am hasving issue with `v0.5.6` and `v0.5.14` and `v0.5.14_oracle`.

On the mbp 16' 2019

**Comment by vvllxxdd** [comment]
Still facing this, any actual solution? No issue linked above actually solved it.

**Comment by ElasticBottle** [comment]
no actual solution for now, I simply ran the thing on a linux // wsl on windows and it worked fine

**Comment by vvllxxdd** [comment]
So basically terrad is unusable on Mac. Superb

**Comment by tgrecojs** [comment]
+1 here

Worth mentioning that, while this seems to be related to the issues the broader cosmos ecosystem is having with go-keychain, the stack trace points directly to CosmWasm when trying to build terrad. 

Ive been able to work around with different go-keychain versions but not luck thus far with terra.

Luckily the LocalTerra repo seems to provide me with an alternative route to getting the functionality i need

**Comment by vvllxxdd** [comment]
It seems pretty unbelievable to me that a project this size doesn't have anyone fixing this, bascially rendering their CLI useless to a pretty big user base.

**Comment by tgrecojs** [comment]
@vvllxxdd This is pretty harsh... 😶 

> It seems pretty unbelievable to me that a project this size doesn't have anyone fixing this, bascially rendering their CLI useless to a pretty big user base.

As i mentioned above, I have been able to run [LocalTerra](https://github.com/terra-money/LocalTerra/) on a docker instance. Have 0 issue running the `terrad` command from within the context of my container.....

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by zmanian** [comment]
I was able to build and use on an m1 Mac with `CGO_ENABLED=1 GOARCH=amd64 make build` and then `cp build/terrad ~/go/bin`. For some reason, `CGO_ENABLED=1 GOARCH=amd64 make install` does not work.

**Comment by vvllxxdd** [comment]
> 

Yeah but the thing is I don't want to use Local Terra, if I wanted a local env I've used that.

**Comment by vvllxxdd** [comment]
> @vvllxxdd This is pretty harsh... 😶
> 
> > It seems pretty unbelievable to me that a project this size doesn't have anyone fixing this, bascially rendering their CLI useless to a pretty big user base.
> 
> As i mentioned above, I have been able to run [LocalTerra](https://github.com/terra-money/LocalTerra/) on a docker instance. Have 0 issue running the `terrad` command from within the context of my container.....


Yeah but the thing is I don't want to use Local Terra, if I wanted a local env I've used that.

**Comment by vvllxxdd** [comment]
> @vvllxxdd This is pretty harsh... 😶
> 
> > It seems pretty unbelievable to me that a project this size doesn't have anyone fixing this, bascially rendering their CLI useless to a pretty big user base.
> 
> As i mentioned above, I have been able to run [LocalTerra](https://github.com/terra-money/LocalTerra/) on a docker instance. Have 0 issue running the `terrad` command from within the context of my container.....

Yeah but the thing is I don't want to use Local Terra, if I wanted a local env I would've used that.

**Comment by gosseti** [comment]
> I was able to build and use on an m1 Mac with `CGO_ENABLED=1 GOARCH=amd64 make build` and then `cp build/terrad ~/go/bin`. For some reason, `CGO_ENABLED=1 GOARCH=amd64 make install` does not work.

I didn’t have any luck doing this unfortunately. Are there any more steps or info you can provide that helped you get it working?

**Comment by vvllxxdd** [comment]
Sorry to say this, but for a 40 bn market cap blockchain you would think there SHOULD be a better dev support and documentation. Instead, everything is deprecated and outdated. Disappointed, wanted to take a fresh breath from EVMs and Solana, but instead i wasted 3 weeks on Terra and didn't make 1 single mainnet transaction from the terminal.

**Comment by gosseti** [comment]
> > I was able to build and use on an m1 Mac with `CGO_ENABLED=1 GOARCH=amd64 make build` and then `cp build/terrad ~/go/bin`. For some reason, `CGO_ENABLED=1 GOARCH=amd64 make install` does not work.
> 
> @zmanian thanks u a lot for this!
> 
> didnt run the `make install`, however running ur modified `make build` cmd succeeded in creating a local `terrad` instance which i then copied from`./build` folder into my go/bin directory. smooth sailing thus far 🙌

@tgrecojs Can you take us through this as a step by step? I’m still yet to get it working and very curious as to how you did it!

**Comment by tgrecojs** [comment]
> @tgrecojs Can you take us through this as a step by step? I’m still yet to get it working and very curious as to how you did it!

@gosseti for me it was rly just a matter of copying that modified make build cmd and running it within the `terra-money/core` repo. 

really straightforward (thankfully) but in the event that it's helpful, the process from start to finish is detailed in snippet below.

```sh
# clone repo && cd into it
~/ git clone https://github.com/terra-money/core && cd core
# execute make build command modified for m1 arch && cd into new build directory 
~/core  CGO_ENABLED=1 GOARCH=amd64 make build
## find go directory using "which"
~/core which go 
/usr/local/go
# copy build/terrad into appropriate directory :)
~/core cp ./build/terrad  /usr/local/go/bin/terrad
```

maybe i lucked out in this instance with everything working so well so quickly... hope u have the same luck tho 🙂

**Comment by gosseti** [comment]
@tgrecojs This is great, thank you for sharing!

When running `which go` it’s reporting a different directory:

```
/opt/homebrew/bin/go
```

I believe this is because homebrew uses the `opt` folder with M1 chips.

And then when copying into there I run into this:

```
cp ./build/terrad /opt/homebrew/bin/go/bin/terrad
# cp: /opt/homebrew/bin/go/bin/terrad: Not a directory
```

Curious as to what method you used to install `go` into the `/usr/local/go` folder? Oh and just to clarify, you’re using an M1 right? (I didn’t see you explicitly mention that above)

**Comment by hanjukim** [comment]
I've successfully compiled native arm64 runtime on my M1 machine without any flag (`make build` and `make install`) by using current `main` branch.

**Comment by StayHomeThereIsNoFrance** [comment]
> I've successfully compiled native arm64 runtime on my M1 machine without any flag (`make build` and `make install`) by using current `main` branch.

Same. It works now. 
But maybe another bug, command `terrad keys add test` doesn't ask for keyring password, just creates key. And commands like `terrad tx bank send test terra1adrress` return error `Error: test.info: key not found`
