### ISSUE TITLE
[BUG] Fail after update to 0.5.20

### ISSUE THREAD

**Issue by panlilu** [terra-money/classic-core#762]
**Describe the bug**
 Fail after update to 0.5.20

logs:

2:32PM INF starting ABCI with Tendermint
2:32PM INF Starting multiAppConn service impl=multiAppConn module=proxy
2:32PM INF Starting localClient service connection=query impl=localClient module=abci-client
2:32PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
2:32PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
2:32PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
2:32PM INF Starting EventBus service impl=EventBus module=events
2:32PM INF Starting PubSub service impl=PubSub module=pubsub
2:32PM INF Starting IndexerService service impl=IndexerService module=txindex
2:32PM INF ABCI Handshake App Info hash="�Rw{W�>\u007f\x05��M\"�_n�D^���v�\x01E�6^���" height=7607790 module=consensus protocol-version=0 software-version=0.5.20
2:32PM INF ABCI Replay Blocks appHeight=7607790 module=consensus stateHeight=7607790 storeHeight=7607791
2:32PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected D952777B57DF3E7F05F7874D229F5F6E8B445E92D9DF76800145B0365E8ABDB1, got 2CE3F5F8D32816AA94CE2951D53476B5F98CC7EDA4C94DD6822BC376C632880F

**To Reproduce**
0.5.19 sync to the latest and update to 0.5.20

**Comment by blocknodehub** [comment]
encounter the same problem

**Comment by awsdataarchitect** [comment]
use this branch
git checkout public-node

**Comment by nyxynyx** [comment]
@awsdataarchitect Tried rebuilding `terrad` from the `public-node` branch but still getting the same error, but on `bombay-12` block 906457.

Here's more details:
- https://github.com/terra-money/classic-core/issues/774

**Comment by awsdataarchitect** [comment]
I used this branch. It worked on Columbus 5 for me. Just start it without any parameters eg the crisis skip assert invariants
