### ISSUE TITLE
message is not supported at height 7650659

### ISSUE THREAD

**Issue by JelloHuang** [terra-money/classic-core#764]
**Describe the bug**

when stating:

failed to execute message; message index: 0: message type *types.MsgDelegate is not supported at height 7650659: message not supported: invalid request

**Comment by immibis** [comment]
They turned off the ability to validate because it would have taken away their control over the network.

A shame, really: the algorithm decided they were unfit to have control, so instead of peacefully giving it up, they changed the algorithm. Turns out it wasn't decentralized after all.
