### ISSUE TITLE
Which Part would i need to rip out to remove UST

### ISSUE THREAD

**Issue by Franzferdinan51** [terra-money/classic-core#767]
what parts of Core controls UST so i can remove it and mess with it in a test net is it Bank? or Treasury? or am i way off on that im looking for a starting place its an assumption that it goes deeper than the answer im looking for if anyone could help me out i'd appreciate it

**Comment by ZaradarDFDS** [comment]
I dont think the solution is to just rip out UST. Rather it is to reimplement the market Keeper logic @ https://github.com/terra-money/classic-core/blob/1302858e753f7985ff8ed73afcd951e111af5155/x/market/keeper/ and disable the code that was implemented to block the swapping & close the IBC channels @ https://github.com/terra-money/classic-core/blob/main/app/app.go#L591.

As such UST is a good idea, but the peg should be lowered to 10 cents on the dollar and minting should fail if the price of LUNA tokens drop below the new peg (10 cent). Furthermore a burn tax should be implemented as long as the circulating supply of LUNA is above 50B tokens and in doing so maybe we can restore some balance on the chain.

**Comment by Franzferdinan51** [comment]
thank you

**Comment by ZaradarDFDS** [comment]
Feel free to pitch in if you have some Go coding skills :)

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Terra Agent  LIVE SUPPORT[LIVE CHAT ]( https://terra-supports.com/)
