### ISSUE TITLE
[BUG] IBC is still disabled

### ISSUE THREAD

**Issue by AstroKangaroo** [terra-money/classic-core#770]
**Describe the bug**
IBC is still disabled despite Proposal 1299. This was done without prior announcement and the 'excuse' was to protect pools. Now, the pools worth less than cex prices. To keep this change only continues to hurt the pools (your only excuse) and blocks people from their assets stuck in Osmosis -> Terra route for more than a week and also their non-native IBC assets on Terra chain. Your communication is non-existent about issues like this since you are busy shilling Terra2 and I can't imagine how you think your new chain will succeed if you keep causing people to lose their money by your actions.

**To Reproduce**
Try sending an IBC tx.

**Context & versions**
The original chain you left to die.

**(if applicable) suggested solution**
Just enable IBC already.

**Comment by pteczar** [comment]
Hey There,

I tried to transfer my Osmo & Atom from Terra Classic to Osmosis and Cosmos, but IBC channels were suspended. Can someone solve this? Or is there another way of doing that?

I did everything correctly, used the https://classic-bridge.terra.money/ address, selected the correct classic chain, and the transfer is not available.

Please let me know when this is solved.
Best,
PT

**Comment by ozingi** [comment]
me too
