### ISSUE TITLE
The IBC channel between Terra and Osmosis is not open

### ISSUE THREAD

**Issue by ozingi** [terra-money/classic-core#780]

**Comment by ozingi** [comment]
> What was the channel id before

72？

**Comment by fragwuerdig** [comment]
Todos for the IBC channel to Osmosis to work again would be as follows

1. Someone needs to run a Cosmos relay node to relay between Osmosis and Terra Classic (see https://github.com/cosmos/relayer)
2. Channel to Osmosis was closed during Terra crash. Reopen by removing line 599 in app.go
3. Would be nice to also alter the relay chain registry at https://github.com/cosmos/chain-registry/blob/master/terra/chain.json
