### ISSUE TITLE
[BUG] restart LUNA but header block hash check failed

### ISSUE THREAD

**Issue by lcgogo** [terra-money/classic-core#788]
**Describe the bug**
```
mbus-5 addr={"id":"4e1c2471efb89239fb04a4b75f9f87177fd91d00","ip":"135.181.55.244","port":26656} module=pex
1:34AM ERR dialing failed (attempts: 1): dial tcp 121.78.241.68:36656: i/o timeout addr={"id":"6828c1731f6146cf2e79633aacdd43971d2a36b5","ip":"121.78.241.68","port":36656} module=pex
1:34AM ERR dialing failed (attempts: 1): dial tcp 3.70.86.72:26656: i/o timeout addr={"id":"c3a22877402264bd03c37d9fc3a910c8cf3e3128","ip":"3.70.86.72","port":26656} module=pex
1:34AM ERR dialing failed (attempts: 1): dial tcp 54.89.127.43:26656: i/o timeout addr={"id":"12e5d8f3602f63644cf548ffc83d886b5715a29f","ip":"54.89.127.43","port":26656} module=pex
1:34AM ERR dialing failed (attempts: 2): dial tcp 35.189.155.44:26656: i/o timeout addr={"id":"69691fcb39455940693133dfaac3e4e337c1f7ef","ip":"35.189.155.44","port":26656} module=pex
1:34AM ERR dialing failed (attempts: 1): dial tcp 195.201.225.154:26656: i/o timeout addr={"id":"437464640c5f3e0a6b1fb6756df21ef115b26ffc","ip":"195.201.225.154","port":26656} module=pex
1:34AM ERR dialing failed (attempts: 1): dial tcp 35.240.133.1:26656: i/o timeout addr={"id":"fd777409b042fe41691011eb6ecdeaad5317f8e9","ip":"35.240.133.1","port":26656} module=pex
1:35AM INF executed block height=9097835 module=state num_invalid_txs=0 num_valid_txs=90
1:35AM INF commit synced commit=436F6D6D697449447B5B3134392031363720383720313520323330203131302036312033332037332031313220313720313434203933203131382032303720323433203232322033312032362032303920323220323335203631203933203230312031343120382031323420323039203531203431203134345D3A3841443236427D
1:35AM INF committed state app_hash=95A7570FE66E3D21497011905D76CFF3DE1F1AD116EB3D5DC98D087CD1332990 height=9097835 module=state num_txs=90
1:35AM INF indexed block height=9097835 module=txindex
panic: Failed to process committed block (9097836:934A209C9DE51B9C91F9A48F538F453F72B4B7947C0EABDB490B963E29A75362): wrong Block.Header.LastResultsHash.  Expected A17D9EF99B580870F2F565F9032B5575358F60AB90045B9FF53D2CCDD35A8BA3, got A9F8FA2365EE84D8273FC1B4E9F2701FFE35241F1920A8807240D2C535EB2DB6

goroutine 291 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0005ab880, 0x0)
	github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x123a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x7a
```
**To Reproduce**
restart lunc

**Context & versions**
0.5.22

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by edk208** [comment]
Something got corrupted... you may have to restart from a snapshot.  Quick sync has some recent snapshots,
https://quicksync.io/networks/terra.html

**Comment by lcgogo** [comment]
> Something got corrupted... you may have to restart from a snapshot. Quick sync has some recent snapshots, https://quicksync.io/networks/terra.html

Tried start from below snapshot, but same.

Download | SanFrancisco | columbus-5-pruned | Checksum | 169G | 2022-08-26 02:41:22 | Hash

Tried the 
git checkout origin/public-node

And similar printout
```
2:12AM INF Starting IndexerService service impl=IndexerService module=txindex
2:12AM INF ABCI Handshake App Info hash="��W\x0f�n=!Ip\x11�]v���\x1f\x1a�\x16�=]ɍ\b|�3)�" height=9097835 module=consensus protocol-version=0 software-version=0.5.22-29-g2d0e9a97
2:12AM INF ABCI Replay Blocks appHeight=9097835 module=consensus stateHeight=9097835 storeHeight=9097836
2:12AM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected A17D9EF99B580870F2F565F9032B5575358F60AB90045B9FF53D2CCDD35A8BA3, got A9F8FA2365EE84D8273FC1B4E9F2701FFE35241F1920A8807240D2C535EB2DB6
Usage:
  terrad start [flags]

Flags:
```

**Comment by jer-lim** [comment]
Quicksync desynced as well, that's what happens when no announcements are made regarding the fork...

**Comment by kingli-crypto** [comment]
Any idea how do we work around this? Our node has been stuck for 2+ days.
Quicksync doesn't work as described above

**Comment by jer-lim** [comment]
> Any idea how do we work around this? Our node has been stuck for 2+ days. Quicksync doesn't work as described above

Last I checked, quicksync netherlands works

**Comment by lcgogo** [comment]
> > Any idea how do we work around this? Our node has been stuck for 2+ days. Quicksync doesn't work as described above
> 
> Last I checked, quicksync netherlands works

@jer-lim  can you share latest addrbook.json, log always show dailing failed 
https://github.com/terra-money/classic-core/issues/790

**Comment by jer-lim** [comment]
> > > Any idea how do we work around this? Our node has been stuck for 2+ days. Quicksync doesn't work as described above
> > 
> > 
> > Last I checked, quicksync netherlands works
> 
> @jer-lim can you share latest addrbook.json, log always show dialing failed #790

[Try this](https://github.com/terra-money/classic-core/files/9451901/addrbook.zip)

**Comment by lcgogo** [comment]
> Any idea how do we work around this? Our node has been stuck for 2+ days. Quicksync doesn't work as described above

tried thess days quicknode netherlands snapshots but always show

```
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected E3B6FF694FB7CAE0874D4A3BCC6A52157DA464F58C9D77E626BA05E1B09ACA93, got 65C04B9670E675F6D32D69B844DD257F23E28C076D99D79BA4A00099B436362A
```

@edk208 @jer-lim @kingli-crypto  any idea?

**Comment by lcgogo** [comment]
Or are there avaible public lunc grpc node? like curl http://public-node.terra.dev:26657/status

**Comment by lcgogo** [comment]
@hanjukim @YunSuk-Yeo  Need some help!

**Comment by lcgogo** [comment]
> > > > Any idea how do we work around this? Our node has been stuck for 2+ days. Quicksync doesn't work as described above
> > > 
> > > 
> > > Last I checked, quicksync netherlands works
> > 
> > 
> > @jer-lim can you share latest addrbook.json, log always show dialing failed #790
> 
> [Try this](https://github.com/terra-money/classic-core/files/9451901/addrbook.zip)

@jer-lim  Can you provide a new addrbook.json for luna classic? The last one is too old now.
