### ISSUE TITLE
[BUG] some validator can't do re-delegations

### ISSUE THREAD

**Issue by Livekus** [terra-money/classic-core#789]
**Describe the bug**
some validators can't do re delegations

**To Reproduce**
click stake -> choose a validator choose re-delegation ->choose PFC-OSS , Orbital Command ,Terra Bites , 01node, or  LUNC DAO

**Context & versions**
Android (App version v2.0.0-161)and web 

log :failed to execute message; message index: 0: too few tokens to redelegate (truncates to zero tokens): invalid request 

**(if applicable) suggested solution**
-

**Comment by edk208** [comment]
Thanks this is not a classic-core error.  I've confirmed that you can re delegate using the terrad binary.  This should go to station as a bug.  I'm trying to figure it out now.

**Comment by Livekus** [comment]
ok I will forward this issue to terra-money
