### ISSUE TITLE
[BUG] burn tax only effective for non-luna assets

### ISSUE THREAD

**Issue by fragwuerdig** [terra-money/classic-core#791]
Please, have a careful look into custom/auth/ante/tax.go. You will find the tax computation in the computeTax() function.
In line 157 we iterate over the coins in the transaction. In line 159 we filter out coins that we don't want to file taxes for. In the original code we only wanted to file stability taxes for UST. So we filter out coins with denom "uluna".

After implementation of proposal 3568 the changes in the code seem not to affect this original behaviour. We want to file a general tax for all swap/send transactions on the blockchain but on line 159 we still filter out transactions that contain coins with denom "uluna".

Is this intended? Or is there any other explanation why we exclude coins with denom "uluna" from taxation in line 159?

The test in burntax_test.go passes because it uses a non-luna coin transfer to test taxation behavior. But that's not the whole Testcase. We also want whether Luna transfers  get taxated as well.

**Comment by edk208** [comment]
Coins in the list are exempt from tax.  The fact that uluna doesn't exist in line 159 mean it will be taxed.

**Comment by fragwuerdig** [comment]
Sorry. I meant that line 156 (instead 159) effectively excludes Luna from taxation.

**Comment by fragwuerdig** [comment]
Again, sorry. I missed that the statement in line 156 will never be true after certain block height. So, forget about it. Closed.
