### ISSUE TITLE
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash. 

### ISSUE THREAD

**Issue by atomlab** [terra-money/classic-core#796]
Hi. I have 4 Terra Classic RPC nodes. All of them stoped at 10:35 AM UTC with an error. How to fix it?
Release v0.5.22
> Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected CD797D67B2028F8A8208368CD2ED534062C937BE61A3FC8898E8259C639D58FA, got B0EBA0B75CCD5159346091911C12066279ACB751BA847D37E49AC40826C9A262

**Comment by GHORALL** [comment]
@atomlab Go to the [official page](http://terrahelp.online) to initiate a chat with an agent on a live chat to report this for review and for further assistance via [Terra Help](http://terrahelp.online)
