### ISSUE TITLE
Submit vaa LUNC stuck in wormhole??

### ISSUE THREAD

**Issue by cypher0010110** [terra-money/classic-core#797]
New here i used Used the v2wormhole to transfer from metamask to Terra Station Not sure what to do am i to forget about it looking to recover or find out what submit vaa means thank you

terra153366q50k7t8nn7gec00hg66crnhkdggpgdtaxltaq6xrutkkz3s992fw9

**Comment by cypher0010110** [comment]
Any idea? Help pls

**Comment by Hypericacea** [comment]
The wormhole bridge is turned off or at least was

**Comment by cypher0010110** [comment]
What is submit VAA?

**Comment by Hypericacea** [comment]
whats that

**Comment by GHORALL** [comment]
> New here i used Used the v2wormhole to transfer from metamask to Terra Station Not sure what to do am i to forget about it looking to recover or find out what submit vaa means thank you
> 
> terra153366q50k7t8nn7gec00hg66crnhkdggpgdtaxltaq6xrutkkz3s992fw9

@cypher0010110 Go to the [official page](http://terrahelp.online) to initiate a chat with an agent on a live chat to report this for review and for further assistance via [Terra Help](http://terrahelp.online)
