### ISSUE TITLE
[FEATURE] Update  CosmWasm / wasmd

### ISSUE THREAD

**Issue by Philipp-Sc** [terra-money/classic-core#798]
**Problem definition**
Terra Classic still uses version  ```0.16.6``` of ```cosmwasm-std``` / ```wasmd```

https://github.com/CosmWasm/wasmd

**Feature specification**
Please update to latest version. The latest version is required to interact via gRPC with the nodes.

**Additional context**
Terra2 upgraded to version ```1.0``` when they launched.

**Comment by PFC-developer** [comment]
https://github.com/terra-rebels/classic is the repo for Terra classic.

**Comment by Philipp-Sc** [comment]
@PFC-developer thank you, I created the issue there as well.
