### ISSUE TITLE
terrad v0.5.23 error

### ISSUE THREAD

**Issue by qlfgggggg** [terra-money/classic-core#802]
**Describe the bug**
error : /data/blockdata/tmphx/terrad: error while loading shared libraries: libwasmvm.so: cannot open shared object file: No such file or directory

**To Reproduce**
Describe the steps to reproduce the behavior.

**Context & versions**
Delineate the correct versions of all the components involved in reproducing the bug. 

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by GHORALL** [comment]
@qlfgggggg Go to the [official page](http://terrahelp.online) to initiate a chat with an agent on a live chat to report this for review and for further assistance via [Terra Help](http://terrahelp.online)
